version: '3'
services:
  db:
    image: postgres:15
    
    environment:
      POSTGRES_DB: lsgco_is_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"