default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  password: password
  host: 0.0.0.0
  port: 5432

development:
  <<: *default
  database: lsgco_is_development

test:
  <<: *default
  database: lsgco_is_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>